### PR TITLE
Prototype for street selection

### PR DESCRIPTION
**Pull request by AtnNn**
I wrote this code after talking to @SundayFunday about the project. Here's a pull request so it doesn't get lost.

This is still missing a lot of functionality:

- prompt user to keep selecting until they get to minimum 1 mile
- all segments must be contiguous
- if street is already adopted, it shouldn’t be selectable
- NCDOT-maintained roads are not in the City’s database, but we want them to be.  When a user wants to adopt a state highway, we want to send them to http://www.ncdot.gov/programs/aah/
- the city wanted the ability to suggest roads, such as those that are more in need of adoption.  Maybe find a way to highlight in a different color or bold those.  These might change on a quarterly, annually, or even monthly basis
- Allow selecting more granular street segments (some segments in this data span multiple street blocks)

### CODE REVIEW

**Comment by tannerhodges** [comment]
Awesome work @AtnNn. I'll check this out over the weekend.

**Comment by tannerhodges** [comment]
@AtnNn Sorry it took me so long for this—looks great! Segmenting the street data was definitely our biggest hurdle. Thanks for this.

Having trouble installing spatialite. Any tips? Running OS X, tried installing [proj.4](https://github.com/OSGeo/proj.4/) and [libgeos](https://github.com/libgeos/libgeos/) but still getting:

```
configure: error: 'libproj' is required but it doesn't seem to be installed on this system.
```

Found a couple notes in Google Groups but haven't had time to read through it all yet.

Btw, where'd you find this mapping software? Found a lot of cool stuff from it, like this guy: http://timogrossenbacher.ch/ Beautiful projects.

Thanks again. Excited to have you on the project.

**Comment by AtnNn** [comment]
I believe spatialite is available through homebrew or macports on OS X.

I found spatialite while looking for a lightweight version of postgis. It can also do [routing](https://www.gaia-gis.it/spatialite-2.3.0/spatialite-network-2.3.0.html) which might be useful.

**Comment by tannerhodges** [comment]
Ah, I'm an idiot—was searching cask instead of brew. Looks like this is all I need then:

```
brew install libspatialite spatialite-tools gdal
npm install -g ogr2ogr
```

2 more questions:
- You recommend any tutorials on Spatialite? Or is this pretty much all I need: http://www.gaia-gis.it/gaia-sins/spatialite-tutorial-2.3.1.html
- Do you use `spatialite-gui`? Figured it'd be nice but just saw there's an issue installing on the latest OS X: https://github.com/Homebrew/homebrew/issues/44003

**Comment by AtnNn** [comment]
I think that tutorial is pretty good. There's also https://www.gaia-gis.it/fossil/libspatialite/wiki?name=misc-docs and http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.3.0.html

I have not used spatialite-gui yet. I've been using qgis, which can read spatialite files.

**Pull request merged**
